name: main

on:
  - push
  - pull_request

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v4

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: pnpm install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          pnpm install
          pnpm install netlify-cli
      - name: build
        run: |
          npm run build
      - name: ci
        run: |
          npm run ci

